### ISSUE TITLE
Alternative Information for Accessing resources 

### ISSUE THREAD

**Issue by toyinolape** [MicrosoftLearning/mslearn-ai900#19]
The learning path - Explore computer vision in Microsoft Azure (Module 1) has some helpful information missing that I noticed is present in the subsequent Modules in the same learning path. 

**Module 1 is below**
![Image without](https://user-images.githubusercontent.com/31407387/124963165-63502b00-e017-11eb-929f-deaa6ce7c337.PNG)

**A subsequent Module is below**
![Image with](https://user-images.githubusercontent.com/31407387/124963190-6cd99300-e017-11eb-93c1-6a388ff5a16c.PNG)

**Comment by sherzyang** [comment]
Hi @toyinolape , thanks for bringing this up. Most of the information you're referring to is now incorporated into the **Note**. I removed some details about the Python environment for those who are not coders. Those who are coders have the option to follow the directions to set up their own environment, which is also linked in the **Note**.
