### ISSUE TITLE
The link contains some characters which generates an error trying to open it

### ISSUE THREAD

**Issue by anmarphy** [MicrosoftLearning/mslearn-ai900#20]
Into the description the link contains at the end some characters +++ that do not belong to the url. After removing them I can access to the material https://docs.microsoft.com/en-us/learn/modules/use-automated-machine-learning/ . I think that would be beneficial correct them

**Comment by sherzyang** [comment]
Hi @anmarphy thanks for raising the issue. I've removed them and will push the change soon.
