### ISSUE TITLE
Typo on file mslearn-ai900/instructions/00 - Local development.md

### ISSUE THREAD

**Issue by lopes-andre** [MicrosoftLearning/mslearn-ai900#23]
There is just a small typo on the file **mslearn-ai900/instructions/00 - Local development.md**.

When referencing to the VS Code's download page, there is an extra ] on the Markdown syntax for the hyperlink. Having [download it here]](https://code.visualstudio.com/Download) instead of [download it here](https://code.visualstudio.com/Download) .

I know it is not a big issue. But I hope to be helpful with these small observations.

Once again, thank you very much for this repo. It is an amazing source for studying and I am translating it to Portuguese to support the Brazilian community.

**Comment by sherzyang** [comment]
Hi @lopes-andre thank you so much for the feedback! I will make a change.
