### ISSUE TITLE
Typo on file mslearn-ai900 / instructions / 00-run-batch.md

### ISSUE THREAD

**Issue by lopes-andre** [MicrosoftLearning/mslearn-ai900#24]
Hello @sherzyang and contributors,

There is another small typo on the file **mslearn-ai900 / instructions / 00-run-batch.md**.

The third, and last, step of the instructions is calling the MSLEARN-AI900 project folder as a file, it says: *"This **file** contains the labs for the course."*

While it should say *"This **folder** contains the labs for the course.*"

As I am translating this repo to Portuguese to help Brazilian students, I am going through each word and finding a couple of typos. If I am being too picky, please let me know and I will stop opening these small issues. I can also fork this repo and suggest a pull request fixing this stuff if I may.

I am sorry if I am misusing it here, I am king of new to GitHub and I am still learning. Please let me know how I should behave when I find this small issues with the repo.

Once again, thank you very much for holding this repo and material. I is simply amazing and helped me a lot towards my AI-900 certification.

**Comment by sherzyang** [comment]
@lopes-andre thanks for letting me know, and for translating this repo for other students. I will make the change.
