### ISSUE TITLE
Error 1007 in lab 08 - Speech.ipynb (Speech synthesis)

### ISSUE THREAD

**Issue by ChusJM** [MicrosoftLearning/mslearn-ai900#29]
In the lab notebook called ["08 - Speech.ipynb"](https://github.com/MicrosoftLearning/mslearn-ai900/blob/main/08%20-%20Speech.ipynb), when executing the code cell below the **Speech synthesis** title, the synthesized audio is not played.

Inspecting the result variable returned in the line `result = speech_synthesizer.speak_text(response_text)` reveals the following error details: "Connection was closed by the remote host. Error code: 1007. Error details: Starting September 1st, 2021 standard voices will no longer be supported for new users.".

This can be solved by manually specifying a neural voice just below the initialization of the `speech_config` variable:

`speech_config.speech_synthesis_voice_name = 'en-US-ChristopherNeural'`

Maybe there's a better option to fix it, but that worked for me.

**Comment by sherzyang** [comment]
Thanks @ChusJM I will go make that correction!
