### ISSUE TITLE
01b and 01c: Access denied

### ISSUE THREAD

**Issue by ngeorgeault** [MicrosoftLearning/mslearn-ai900#3]
In these 2 scenarios, when we try to consume the model in the Python notebook, even if details are correct about endpoint, project and key, you'll receive an "Access denied".

**Comment by sherzyang** [comment]
Hi @ngeorgeault thanks for writing. There are a few parts in these two labs where it's easy to run into errors if a step is missed. I've had it happen myself. 

I suggest a few things: 
1. Check in - at the start of the lab, did you create a **Cognitive Service** resource or **Custom Vision** resource? Both can be used, but there are steps that differ for the two later in the lab. 
2. Check in - when you published your model, did you use the exact name "groceries"? You can see in the cell asking for the endpoint, project ID, and key, it references the model name "groceries" with that exact spelling and lowercase letters. 
3. If you created a **Custom Vision** resource at the start of your lab, you will only get your project ID from this Project Settings page: 
![image](https://user-images.githubusercontent.com/19577448/114798240-c0568080-9d49-11eb-9be1-ee7402411c95.png)
You will need to follow steps 11-12 to navigate to the resources page to get your endpoint and key. You need to select the endpoint and key associated with the **prediction** resource, not the **training** resource. 
![image](https://user-images.githubusercontent.com/19577448/114798347-04498580-9d4a-11eb-85bd-14336866aec0.png)
4. If you created a **Cognitive Service** resource at the start of your lab, you can use the Project Settings Page to retrieve your project ID, endpoint, and key. 

Hope this helps resolve your access issue. If it does not, please let me know.
