### ISSUE TITLE
Unrecognized cmdlet in understand.ps1, line 20

### ISSUE THREAD

**Issue by RobertSPratt** [MicrosoftLearning/mslearn-ai900#30]
When working on the *Create a language model with Language Understanding* module's Exercise - Create a Language Understanding Application, I received a `The term '-like' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again` error (shown in the attached screenshot) for `Line 20`: `if($predictedDevice -like ("*light*") -or (-like ("*fan*"))){`. I have not modified anything outside of what the exercise calls for (the `$appId`, `$key`, and `$endpointUrl` variables).
![ai-900_error_understand_ps1](https://user-images.githubusercontent.com/59897760/143323102-87e23c0d-e4a6-4b18-8a91-4bcbe8a3efba.png)

**Comment by sherzyang** [comment]
@RobertSPratt Thanks so much for sharing. I've pushed a fix to this issue. I believe you may have been working on the lab from Learn and then submitted an issue to this **mslearn-ai900** repo, which contains the Python notebook version of the labs. The labs on Learn use PowerShell now and reference this repo **ai-900-aifundamentals**: https://github.com/microsoftlearning/ai-900-aifundamentals. 

You can find the Learn instructions and reference to the **ai-900-aifundamentals** repo for the Language Understanding lab here: 
https://docs.microsoft.com/en-us/learn/modules/create-language-model-with-language-understanding/3-exercise-create-language-understanding-application
