### ISSUE TITLE
Custom Vision 

### ISSUE THREAD

**Issue by hamzahamidi** [MicrosoftLearning/mslearn-ai900#4]
I keep getting the following error whenever I try to create a new project in https://www.customvision.ai/projects for the labs 2 and 3.

I tried both S0 and F0 plans for the custom vision, But I still get the same error.

```json
{
    "error": {
        "code": "TooManyRequests",
        "message": "The request is being throttled as the limit has been reached for operation type - Write_ObservationWindow_01:00:00. For more information, see - https://aka.ms/srpthrottlinglimits"
    }
}
```

![image](https://user-images.githubusercontent.com/22576950/111343443-b9215180-867b-11eb-9481-626b60bbd8c5.png)

**Comment by sherzyang** [comment]
@hamzahamidi I haven't gotten other reports of this issue. I don't think it's related to the pricing tier, but as the link https://aka.ms/srpthrottlinglimits suggests, concurrent read, write, list operations exceeding the limit at a given time. I wonder if there were other projects going on while you worked on the lab that utilized your resource group. If you are still facing this issue, I'd suggest putting in a new support request in the Azure Portal: https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview
