### ISSUE TITLE
Cannot import ComputerVisionClient with azure-cognitiveservices-vision-computervision 0.7.0

### ISSUE THREAD

**Issue by KnowledgeSharer1337** [MicrosoftLearning/mslearn-ai900#7]
Dear Sir or Madam,

in this [file](https://github.com/MicrosoftLearning/mslearn-ai900/blob/main/01%20-%20Image%20Analysis%20with%20Computer%20Vision.ipynb) it is not possible to execute the following command without getting an exception/error using `azure-cognitiveservices-vision-computervision 0.7.0`:

`from azure.cognitiveservices.vision.computervision import ComputerVisionClient`

I had to downgrade to `azure-cognitiveservices-vision-computervision 0.5.0` through `pip install azure-cognitiveservices-vision-computervision==0.5.0` to make the mentioned command work.

With best regards

**Comment by sherzyang** [comment]
Hi @KnowledgeSharer1337 thanks for writing. I just tested the referenced notebook - lab 1,  and it has been running with `azure-cognitiveservices-vision-computervision 0.7.0`. Let me know if you continue to have issues, you should not have to install version 0.5.0 to use the lab.
